### ISSUE TITLE
Q: Update to more state-of-the art .gitattributes suggestions?

### ISSUE THREAD

**Issue by adswa** [ReproNim/module-reproducible-basics#35]
The version control part in this module suggests the following addition to ``.gitattributes`` in the task "How can we add the file a.txt directly under git, and file b.dat under git-annex?":

```
% cat << EOF > .gitattributes
* annex.largefiles=(not(mimetype=text/*))
*.dat annex.largefiles=anything
EOF
```

I have two remarks: 

First, if someone follows the exercise, this command may fail or do something unexpected, because if executed in the git-annex repo of the previous exercise, this here doc would overwrite an existing .gitattributes file.

Second, with this configuration, empty (text)files would be annexed (see https://github.com/datalad/datalad/issues/3663). I would suggest using the current configuration that datalad's ``text2git`` procedure uses: `((mimeencoding=binary)and(largerthan=0))`.

I'll send a PR later today that demonstrates what I mean.

**Comment by yarikoptic** [comment]
Closed by https://github.com/ReproNim/module-reproducible-basics/pull/36#merged-event
